### ISSUE TITLE
Docker issue: mounts denied

### ISSUE THREAD

**Issue by optimass** [ElementAI/synbols#19]
Hello, I ran into this issue when first launching the `synbols-datasets` command.

`synbols-datasets --dataset=some-large-occlusion --n_samples=1000 --seed=42`

`Synbols (0.1.0.dev3) found at /opt/anaconda3/lib/python3.7/site-packages/synbols
Unable to find image 'aldro61/synbols:v0.1.0.dev3' locally
v0.1.0.dev3: Pulling from aldro61/synbols
7595c8c21622: Pull complete
d13af8ca898f: Pull complete
70799171ddba: Pull complete
b6c12202c5ef: Pull complete
15e08a590eba: Pull complete
cd998673c011: Pull complete
4d8041a92e4a: Pull complete
5351f89ccada: Pull complete
fbd89ae99554: Pull complete
803114100336: Pull complete
5223744c8f43: Pull complete
36e312d0ca9f: Pull complete
212a527b1b9e: Pull complete
a54201ff6358: Pull complete
dbac0eb89eb3: Pull complete
b2250472f2fb: Pull complete
bf2d0833e720: Pull complete
be14cd6dbd4e: Pull complete
8c2ba46a7b73: Pull complete
8936dbe7551e: Pull complete
Digest: sha256:8b263c4bab28292c155f77fa6e31cd153e8120335e435e30151ce8cbf10effd5
Status: Downloaded newer image for aldro61/synbols:v0.1.0.dev3
docker: Error response from daemon: Mounts denied:
The paths /opt/anaconda3/lib/python3.7/site-packages/synbols/entrypoints and /opt/anaconda3/lib/python3.7/site-packages/synbols
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0110] error waiting for container: context canceled`

Thanks for helping!

**Comment by aldro61** [comment]
Hi @optimass! 

It looks like the `synbols` package is installed at a path that cannot be accessed by Docker. Your anaconda installed in `/opt`, so you might have to explicitly allow Docker to access this path. Please do the following:

1) Go the the Docker preferences, under `Preferences -> Resources -> File sharing`
2) Make sure that the problematic path appears here, i.e., `/opt`

On MacOS, you should see something like this:
![image](https://user-images.githubusercontent.com/2374980/92813396-17990a80-f38f-11ea-89b4-2632d01a12f3.png)

I hope this helps!

**Comment by optimass** [comment]
awesome, it worked 👍
