### ISSUE TITLE
Synbols' docker break when there is a space in the installation path

### ISSUE THREAD

**Issue by recursix** [ElementAI/synbols#30]
to reproduce:
git clone synbols in a directory that contains a space
pip install -e <directory with space>/synbols

**Comment by aldro61** [comment]
@recursix I tried moving my `synbols` directory to `synbols space` to test and it still works. However, I `cd synbols\ space` and then `pip install -e .`, not `pip install -e /synbols`.

![Screen Shot](https://user-images.githubusercontent.com/2374980/104614516-53522280-5656-11eb-98db-4b37c4acbced.png)

**Comment by aldro61** [comment]
Ok I can reproduce the issue when using `synbols-datasets`
![Screen Shot](https://user-images.githubusercontent.com/2374980/104617145-176c8c80-5659-11eb-8553-09be2d0f4935.png)

**Comment by aldro61** [comment]
Simple fix is to add single quotes around `file` here https://github.com/ElementAI/synbols/blob/master/synbols/entrypoints/run_docker.py#L94

**Comment by recursix** [comment]
LGTM
