### ISSUE TITLE
Reproduction with Synbols_100K

### ISSUE THREAD

**Issue by wwd29** [ElementAI/synbols#32]
Hi, when I want to reproduce the Synbols_100K，with the script,
`synbols-datasets --dataset default --n_samples 100000 --seed 42` 
I got,
Generating default dataset. Info: Generate the default dataset,
    using gradiant as foreground and background.

Preview generated.
 12%|#########1                                                                  | 11975/100000 [04:09<28:40, 51.16it/s]/data/examples/entrypoints/synbols/drawing.py:35: RuntimeWarning: divide by zero encountered in double_scalars
  font_size = attributes.scale / max(extent.width, extent.height)
 12%|#########1                                                                  | 11975/100000 [04:09<30:36, 47.92it/s]
Traceback (most recent call last):
  File "entrypoints/generate_datasets.py", line 78, in <module>
    main()
  File "entrypoints/generate_datasets.py", line 70, in main
    write_h5(file_path + ".h5py", ds_generator, args.n_samples)
  File "/data/examples/entrypoints/synbols/data_io.py", line 101, in write_h5
    for i, (x, mask, y) in enumerate(dataset_generator):
  File "/data/examples/entrypoints/synbols/generate.py", line 326, in make_preview
    for x, mask, y in generator:
  File "/data/examples/entrypoints/synbols/generate.py", line 277, in dataset_generator
    mask = attributes.make_mask()
  File "/data/examples/entrypoints/synbols/drawing.py", line 430, in make_mask
    mask_list.append(symbol.make_mask(self.resolution))
  File "/data/examples/entrypoints/synbols/drawing.py", line 515, in make_mask
    draw_symbol(ctxt, self)
  File "/data/examples/entrypoints/synbols/drawing.py", line 38, in draw_symbol
    extent = ctxt.text_extents(char)
cairo.Error: invalid matrix (not invertible)

I found the last `ctxt.width` and `ctxt.height` are zero, so did you meet this problem?

**Comment by recursix** [comment]
Thanks for reporting.

I cannot reproduce with synbols 1.0.3. Can you confirm this is the version you are using?

Are you running in the docker? 
I cannot reproduce with the current docker.

**Comment by recursix** [comment]
Thanks for reporting!

When there is a symbol that is not visible for a given font, it creates a division by zero. Our filters are supposed to catch all of these but seems like there is a specific combination of symbol + font that sneaked through those filters. 

I added a quick fix to avoid division by zero. we'll upgrade the version and push a new package.

**Comment by aldro61** [comment]
Fixed version (1.0.2) pushed to pypi (https://pypi.org/project/synbols/1.0.2/). @recursix you can close if you're done.

**Comment by wwd29** [comment]
Thanks for your reply
